var quotes = [
    "Do you know why dentists are always so cheerful? Because they have people's lives in their hands. The moment they slip up, the whole thing ends. One wrong twist of the wrist and BANG! Goes the enamel.",
    "Why so serious? All you need's a little lipstick.",
    "Introduce a little anarchy. Upset the established order, and everything becomes chaos. I do love chaos.",
    "Madness is like gravity, all it takes is a little push.",
    "You see, madness is the very point! How can they arrest someone who breaks no laws?",
    "Gotham's not about order. It's about... balance.",
    "What doesn't kill you, simply makes you... stranger.",
    "Introduce a little anarchy. Upset the established order, and everything becomes chaos. I do love chaos.",
    "They won't kill you out of some misplaced sense of self-preservation. They won't grant you the satisfaction of taking it from them. They'll just lock you away.",
    "I'm not a monster, I'm an agent of chaos.",
    "I don't want to kill you because you're just too much fun. I think you and I are destined to do this forever.",
    "Do I really look like a guy with a plan?",
    "All it takes is one bad day to reduce the sanest man alive to lunacy. That's how far the world is from where I am. Just one bad day.",
    "Because some men just want to watch the world burn.",
    "You have nothing, nothing to threaten me with. Nothing to do with all your strength.",
    "Isn't it pretty to think so? Humans are creatures of habit. The predictable. They expect routine. And when routine fails them... they resort to violence. How very predictable.",
    "It's all part of the plan.",
    "Clowns are freaks when they're alone in the dark. But in a crowd, they're just... entertainment.",
    "Why so serious? It's not about money, it's about sending a message. Everything burns.",
    "I like magic. Makes people disappear.",
    "We all wake up in a different world.",
    "It started as a whisper, but it became a buzz.",
    "You think I'm afraid to die?",
    "We have to learn to accept who we are.",
    "I’m no good for you, but I’m no good for anyone.",
    "If you weren't real, then how could I be?",
    "I'm not a criminal. I'm an artist.",
    "I am going to change the face of British society.",
    "You don’t get to say no.",
    "When you're dead already, you're free.",
    "If you can't see the angles no more, you're in trouble.",
    "For them, family is a weakness. For us, family is a strength.",
    "I'm not God. Not yet.",
    "Fear is the mind-killer.",
    "In war, there are no unwounded soldiers.",
    "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.",
    "We will be free, we will be masters of our own land.",
    "Your time is up.",
    "One bullet can change the course of history.",
    "For all our freedoms, we pay a price.",
    "We’re a team. We stick together.",
    "Don't waste my time.",
    "Live every moment.",
    "We are not men. We are more than that.",
    "Everybody calm the fuck down!",
    "You either die a hero or live long enough to see yourself become the villain.",
    "Why do we fall? So we can learn to pick ourselves up.",
    "I'm not wearing hockey pads.",
    "A hero can be anyone.",
    "Do you want to see my mask?",
    "It's not who I am underneath, but what I do that defines me.",
    "I never said thank you.",
    "I won’t kill you, but I don’t have to save you.",
    "Some men just want to watch the world burn.",
    "You have to do the hard things.",
    "Do not go gentle into that good night.",
    "We’re not meant to save the world. We’re meant to leave it.",
    "Love is the one thing that transcends time and space.",
    "We must confront the reality of interstellar travel.",
    "Mankind was born on Earth. It was never meant to die here.",
    "Dreams feel real while we're in them.",
    "An idea is like a virus.",
    "You mustn't be afraid to dream a little bigger, darling.",
    "We need to go deeper.",
    "You’re waiting for a train.",
    "I'm just doing what you taught me.",
    "The mind is the scene of the crime.",
    "You're a haunted man.",
    "You are the smartest guy I ever met.",
    "Our lives are defined by opportunities, even the ones we miss.",
    "No one can be told what the Matrix is.",
    "Every man has his breaking point.",
    "A bullet tells the truth.",
    "Don’t let me lose myself.",
    "Memory is a monster.",
    "I have to believe in a world outside my own mind.",
    "We all need mirrors to remind ourselves who we are.",
    "You don’t want the truth. You make up your own truth.",
    "Time is an illusion.",
    "What’s happened, happened.",
    "We live in a twilight world.",
    "Don’t try to understand it. Feel it.",
    "The bullet's been inverted.",
    "To do what I do, I need some idea of the threat we face.",
    "It’ll open the right doors, some of the wrong ones too.",
    "Dying alone would be a lot worse.",
    "We’re the people saving the world from what might have been.",
    "How would you like to die?",
    "We’re getting the band back together.",
    "The secret impresses no one.",
    "Are you watching closely?",
    "You always were the better magician.",
    "Man's reach exceeds his imagination.",
    "The audience knows the truth.",
    "The world is simple, but it’s designed to be complicated.",
    "Hope is a weapon. Survival is victory.",
    "We shall fight on the beaches.",
    "You can practically see it from here.",
    "Home.",
    "Wars are not won by evacuations.",
    "There is no hiding from this, son.",
    "They’ll come back, won’t they?",
    "All we did is survive.",
    "Superiority at sea.",
    "We have a job to do.",
    "The enemy is closing in.",
    "I don’t want to set the world on fire.",
    "We’re going to need a bigger boat.",
    "Fear is the mind-killer.",
    "The spice must flow.",
    "I must not fear. Fear is the mind-killer.",
    "He who controls the spice controls the universe.",
    "I am the one who will die.",
    "The sleeper must awaken.",
    "One day, the legend will be born.",
    "This is only the beginning.",
    "My name is a killing word.",
    "A secret is a powerful thing.",
    "Obsession is a young man’s game.",
    "The world is made of secrets."
];